### PR TITLE
Update tsconfig.json

### PR DESCRIPTION
**Pull request by codewithpom**

### CODE REVIEW

**Comment by beenotung** [comment]
If your goal is to reduce output size, you may change the build target to es6. Or even better, tryout stencil.js

**Comment by beenotung** [comment]
For this package, I prefer to keep it identical to the template generated from "create-react-app --template typescript".

The primary goal of this package is to remove dependency on npm (I use pnpm), and to allow expanding the template without extra steps involving installing additional template installer (create-react-app is installing and uninstalling additional packages during the creation process)

**Comment by codewithpom** [comment]
@beenotung Even I use pnpm but I think that you should add if you want

**Comment by beenotung** [comment]
I will support it with additional parameters

**Comment by codewithpom** [comment]
ok cool

**Comment by beenotung** [comment]
I wonder how much build size can you shrink with the suggested settings.

I tried to build a non-trivial project w/wo the suggested tsconfig flags, the different on output size is neglectable.
I removed non-code files before measures, (removed images, *LICENSE.txt, and *.map).
The size is measured by `du -sh --apparent-size build`, both shows 1.9M.

**Pull request closed without merging**
